const LANGUAGE = (() => {
    const languages = [
        "Afar",
        "Afrikaans",
        "Aghem",
        "Akan",
        "Albanian",
        "Amharic",
        "Arabic",
        "Armenian",
        "Assamese",
        "Asturian",
        "Asu",
        "Azerbaijani",
        "Bafia",
        "Bamanankan",
        "Bangla",
        "Basaa",
        "Bashkir",
        "Basque",
        "Belarusian",
        "Bemba",
        "Bena",
        "Blin",
        "Bodo",
        "Bosnian",
        "Breton",
        "Bulgarian",
        "Burmese",
        "Catalan",
        "Cebuano",
        "Central Atlas Tamazight",
        "Central Kurdish",
        "Chakma",
        "Chechen",
        "Cherokee",
        "Chiga",
        "Chinese",
        "Church Slavic",
        "Colognian",
        "Cornish",
        "Corsican",
        "Croatian",
        "Czech",
        "Danish",
        "Divehi",
        "Duala",
        "Dutch",
        "Dzongkha",
        "Embu",
        "English",
        "Esperanto",
        "Estonian",
        "Ewe",
        "Ewondo",
        "Faroese",
        "Filipino",
        "Finnish",
        "French",
        "Friulian",
        "Fulah",
        "Galician",
        "Ganda",
        "Georgian",
        "German",
        "Greek",
        "Guarani",
        "Gujarati",
        "Gusii",
        "Hausa",
        "Hawaiian",
        "Hebrew",
        "Hindi",
        "Hungarian",
        "Icelandic",
        "Igbo",
        "Inari Sami",
        "Indonesian",
        "Interlingua",
        "Inuktitut",
        "Irish",
        "isiXhosa",
        "isiZulu",
        "Italian",
        "Japanese",
        "Javanese",
        "Jola-Fonyi",
        "Kabuverdianu",
        "Kabyle",
        "Kako",
        "Kalaallisut",
        "Kalenjin",
        "Kamba",
        "Kannada",
        "Kashmiri",
        "Kazakh",
        "Khmer",
        "Kikuyu",
        "Kinyarwanda",
        "Kiswahili",
        "Konkani",
        "Korean",
        "Koyra Chiini",
        "Koyraboro Senni",
        "Kwasio",
        "Kyrgyz",
        "K'iche'",
        "Lakota",
        "Langi",
        "Lao",
        "Latvian",
        "Lingala",
        "Lithuanian",
        "Low German",
        "Lower Sorbian",
        "Luba-Katanga",
        "Lule Sami",
        "Luo",
        "Luxembourgish",
        "Luyia",
        "Macedonian",
        "Machame",
        "Makhuwa-Meetto",
        "Makonde",
        "Malagasy",
        "Malay",
        "Malayalam",
        "Maltese",
        "Manx",
        "Maori",
        "Mapuche",
        "Marathi",
        "Masai",
        "Mazanderani",
        "Meru",
        "Meta'",
        "Mohawk",
        "Mongolian",
        "Morisyen",
        "Mundang",
        "N'Ko",
        "Nama",
        "Nepali",
        "Ngiemboon",
        "Ngomba",
        "North Ndebele",
        "Northern Luri",
        "Northern Sami",
        "Norwegian Bokmål",
        "Norwegian Nynorsk",
        "Nuer",
        "Nyankole",
        "Occitan",
        "Odia",
        "Oromo",
        "Ossetic",
        "Pashto",
        "Persian",
        "Polish",
        "Portuguese",
        "Prussian",
        "Punjabi",
        "Quechua",
        "Romanian",
        "Romansh",
        "Rombo",
        "Rundi",
        "Russian",
        "Rwa",
        "Saho",
        "Sakha",
        "Samburu",
        "Sango",
        "Sangu",
        "Sanskrit",
        "Scottish Gaelic",
        "Sena",
        "Serbian",
        "Sesotho",
        "Sesotho sa Leboa",
        "Setswana",
        "Shambala",
        "Shona",
        "Sindhi",
        "Sinhala",
        "siSwati",
        "Skolt Sami",
        "Slovak",
        "Slovenian",
        "Soga",
        "Somali",
        "South Ndebele",
        "Southern Sami",
        "Spanish",
        "Standard Moroccan Tamazight",
        "Swedish",
        "Swiss German",
        "Syriac",
        "Tachelhit",
        "Taita",
        "Tajik",
        "Tamil",
        "Tasawaq",
        "Tatar",
        "Telugu",
        "Teso",
        "Thai",
        "Tibetan",
        "Tigre",
        "Tigrinya",
        "Tongan",
        "Turkish",
        "Turkmen",
        "Ukrainian",
        "Upper Sorbian",
        "Urdu",
        "Uyghur",
        "Uzbek",
        "Vai",
        "Venda",
        "Vietnamese",
        "Volapük",
        "Vunjo",
        "Walser",
        "Welsh",
        "Western Frisian",
        "Wolaytta",
        "Wolof",
        "Xitsonga",
        "Yangben",
        "Yi",
        "Yiddish",
        "Yoruba",
        "Zarma"
    ];
    Object.freeze(languages);
    return languages;
})();

document.querySelector("main")
.appendChild(document.createElement("ul"))
.appendChild(LANGUAGE.reduce((fragment, language) => {
    const item = document.createElement("li");
    item.dataset.value = language.toLowerCase();
    fragment.appendChild(item);
    return fragment;
}, document.createDocumentFragment()));